-- Files generated by agents (phase 2) and the private Storage bucket that holds them.
-- Null rule: minimal fields are not null; everything else accepts null.

create table public.artifacts (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null
        default '00000000-0000-0000-0000-000000000001'
        references public.workspaces (id) on delete cascade,
    task_id uuid not null references public.tasks (id) on delete cascade,
    agent_id uuid not null references public.agents (id) on delete cascade,
    type text not null,
    status text not null default 'generating',
    created_at timestamptz not null default now(),
    title text,
    mime text,
    storage_path text,
    size_bytes bigint,
    source_spec jsonb,
    error jsonb,
    constraint artifacts_type_valid check (type in ('docx', 'pptx', 'md')),
    constraint artifacts_status_valid check (status in ('generating', 'ready', 'failed')),
    constraint artifacts_size_positive check (size_bytes is null or size_bytes >= 0)
);

create index artifacts_task_created_idx on public.artifacts (task_id, created_at);

insert into storage.buckets (id, name, public)
values ('artifacts', 'artifacts', false)
on conflict (id) do nothing;
